### ISSUE TITLE
Snowflake - get_columns

### ISSUE THREAD

**Issue by SudhirNune** [bitpicky/dbt-sugar#211] opened 2021-04-13 19:55 UTC
def - **get_columns_from_table** in **_dbt_sugar\core\connectors\base.py_**, is a costly, as its pulling down the every table in the Schema and once the data is back in to the python definition and then its applying the table name Filter which is costly, as for every Model, it fetches the whole dump of **Information_schema.columns & Primary keys** from the schema 

1. SHOW /* sqlalchemy:_get_schema_primary_keys */PRIMARY KEYS IN SCHEMA **<<DB Name>>.<<Schema Name>>**
2. SELECT /* sqlalchemy:_get_schema_columns */
                   ic.table_name,
                   ic.column_name,
                   ic.data_type,
                   ic.character_maximum_length,
                   ic.numeric_precision,
                   ic.numeric_scale,
                   ic.is_nullable,
                   ic.column_default,
                   ic.is_identity,
                   ic.comment
              FROM information_schema.columns ic
             WHERE ic.table_schema= **<<Schema Name>>**
             ORDER BY ic.ordinal_position

Suggestion is to go with **desc table** which provide both the column name & Primary Keys in one call.

**Comment by bastienboutonnet** [comment] 2021-04-14 10:01
Hi again @SudhirNune really appreciate the feedback. Info schemas on snowflake are indeed really rich. `desc table` might indeed be a good approach here. 

I'm gonna have to give it some thought. I'll plan this most likely into the next feature release but will let you know as soon as you can give a test to the beta.

The issue is that I don't have access to a snowflake warehouse anymore so testing it might be a little tricky.

Do you think you could help testing it if I get a PR going? Or maybe do you feel like implementing it yourself entirely?

**Comment by bastienboutonnet** [comment] 2021-04-14 10:07
@virvirlopez do you think you could help here with testing if @SudhirNune isn't able to open a PR?

**Comment by SudhirNune** [comment] 2021-04-14 11:20
@bastienboutonnet - I can help with the testing

**Comment by SudhirNune** [comment] 2021-04-14 11:23
@bastienboutonnet  - Below can be a simple change which does the trick for you

con = engine.connect()
rs = con.execute('DESC TABLE '+<<SCHEMA NAME>>+'.'+<<TABLENAME>>)
df = DataFrame(rs.fetchall())
df.columns = rs.keys()
columns_names = [k.upper() for k in df["name"]]

**Comment by bastienboutonnet** [comment] 2021-04-14 11:31
Awesome thanks for the testing offer. And thanks for the snippet. It makes sense. I'll likely have some time over the weekend but if you would like this to move faster feel free to contribute a code change directly.

**Comment by bastienboutonnet** [comment] 2021-04-14 15:48
@SudhirNune looking at the snowflake-sqlalchemy codebase, I'm wondering why they don't use `describe` themselves (https://github.com/snowflakedb/snowflake-sqlalchemy/blob/e1141b8ddfbc499d1b813ae1b791a0559312e6cb/snowdialect.py#L403)

It seems to me that it would make more sense for this to be addressed in their code base at some point don't you think?

I'm ok with the idea of implementing our own version of `get_columns` which uses the `describe` statement but I don't really like it as a long term solution. The whole point of using sqlalchemy is that we don't have to implement dialect ourselves here. This comes at a cost of having to test that our re-implementations are solid etc.

What do you think?

**Comment by bastienboutonnet** [comment] 2021-04-14 16:32
Here's an issue/question I asked to the developers of the sqlalchemy plugin: https://github.com/snowflakedb/snowflake-sqlalchemy/issues/221

**Comment by SudhirNune** [comment] 2021-04-14 16:43
@bastienboutonnet  - I agree with you, but we have the base.py which we created to have the customization you like to have, so making our own version of **get_columns_from_table** is good approach. Later when we see a release from **sqlalchemy** then it can be always added / enhanced

**Comment by bastienboutonnet** [comment] 2021-04-14 18:14
@SudhirNune yeah I agree! I don't like to have it so and I would prefer the snowflake connector itself to be more performant but I'm sure I can act faster than they will.

My only concern is with the comment that was made on a related ticket (which an ex-colleague of mine raised funnily enough) https://github.com/snowflakedb/snowflake-sqlalchemy/issues/204#issuecomment-757489400 which might explain why they went for a full info schema query. Seems a bit stupid though...

**Comment by SudhirNune** [comment] 2021-04-14 20:27
@bastienboutonnet - do you want me to go with a PR with the update code or let the other issue solve it ?

**Comment by bastienboutonnet** [comment] 2021-04-14 20:46
@SudhirNune I've started something here: https://github.com/bitpicky/dbt-sugar/pull/212

One thing I'd like to do is ability to choose the describe Vs vanilla version in case people would prefer it as it may be a safer option if this 10k limit thing is true. Although to be honest I don't think it would ever be hit...

So that means I'd have to make a further change in the config to toggle the method on and off. 

Do you feel like trying out this patch?

**Comment by SudhirNune** [comment] 2021-04-14 21:34
@bastienboutonnet  - the code is good, we can proceed with the change

**Comment by bastienboutonnet** [comment] 2021-04-15 08:34
@SudhirNune It's not finished yet, I want to implement a feature flag that points to the sqlachmy method by default for now and let people opt into the describe method at least in the begining.

Did you actually end up running it yesterday or does it just look good to you?

**Comment by bastienboutonnet** [comment] 2021-04-18 12:15
Hi again @SudhirNune, @virvirlopez and I were able to test this new method on a snowflake warehouse and it is indeed so much faster.

The code-change was just merged here: https://github.com/bitpicky/dbt-sugar/pull/212

Would you like me to push an alpha release of `0.1.0` for you to test?

**Comment by bastienboutonnet** [comment] 2021-04-18 12:15
Resolved in #212

**Closed by bastienboutonnet** 2021-04-18 12:15 UTC
Labels: connector: snowflake ❄️, enhancement, good first issue, help wanted, size: small
