### ISSUE TITLE
ignore formatting/cleanup of specific .yml files

### ISSUE THREAD

**Issue by diegodewilde** [bitpicky/dbt-sugar#294] opened 2021-06-17 13:01 UTC
**Is your feature request related to a problem? Please describe.**
We're struggling with the auto formatting (and especially cleaning) of some `yml` files.  
It seems that it also removes comments for files (such as configurations for other processes that are using .yml files as well).  
Those comments are necessary and shouldn't be removed. 

**Describe the solution you'd like**
There are 2 solutions imo: 
- Provide an ignore section for files to be excluded from the formatting/cleaning process
- Only format/clean dbt related `yml` files (e.g. starting with version: 2). 

Thanks in advance!

**Comment by bastienboutonnet** [comment] 2021-06-17 17:25
@diegodewilde thanks for the issue report. 

Just so I can make sure I understand. Does it clean also non schema files (i.e. yaml that is not a model descriptor?)

Could you also maybe provide a sample of a file that it is cleaning up and how it should look instead in your opinion so I can have a reproduction test case to develop against ?

**Comment by diegodewilde** [comment] 2021-06-18 07:04
Hi @bastienboutonnet 

Yes, it cleans non-schema files. To have a test case, you can use an example `.gitlab-ci.yml` file.   
I've added the `# NEVER REMOVE THIS COMMENT` section, which is being removed. 

```yaml
stages:
  - build
  - test

# NEVER REMOVE THIS COMMENT
build-code-job:
  stage: build
  script:
    - echo "Check the ruby version, then build some Ruby project files:"
    - ruby -v
    - rake

test-code-job1:
  stage: test
  script:
    - echo "If the files are built successfully, test some files with one command:"
    - rake test1

test-code-job2:
  stage: test
  script:
    - echo "If the files are built successfully, test other files with a different command:"
    - rake test2
```
    
Hope this can help you for a reproduction test case.
Thanks in advance and enjoy the weekend ahead!

**Comment by bastienboutonnet** [comment] 2021-06-18 07:26
Thanks @diegodewilde that's indeed not great. This should help enough. I will have a look as soon as I can (these days it's a bit busy) if you have a fix in mind and want to speed it up by contributing feel free to and I can support if not I think I should have some time over the weekend.

**Comment by diegodewilde** [comment] 2021-06-21 10:28
Hi @bastienboutonnet 

After some more exploration, it seems that it's removing all comments in .yml files related to dbt files as well.
I guess the best solution to be to have the possibility to disable this 'feature' and don't remove the comments at all. 

What's your opinion about it?

**Comment by bastienboutonnet** [comment] 2021-06-21 16:08
> Hope you had a great weekend! Unfortunately, I don't have much spare time atm to help contributing.
I did thanks, I didn't have much of a chance to sit behind the computer either. I really need to find some time because it's preventing eager early-adopters like you to move forward with the tool though. And no worries about not finding the time, I know the feeling all too well myself.

> After some more exploration, it seems that it's removing all comments in .yml files related to dbt files as well.
I guess the best solution to be to have the possibility to disable this 'feature' and don't remove the comments at all.

Yeah I assumed it would. I think your idea isn't too bad, at least as a quick fix maybe? Ideally, I'd have some proper AST parsing of it so that I can maybe make sure I put the comments back to where they belong. But that might require a bit more validation and research so I'll have to find a way to allow a temporary solution and I think the "do not cleanup" CLI flag makes sense at this point.

**Comment by bastienboutonnet** [comment] 2021-06-22 19:11
Adding this for when I get round to looking into this. Ruamel yaml might support comments: https://stackoverflow.com/questions/7255885/save-dump-a-yaml-file-with-comments-in-pyyaml/27103244

**Comment by bastienboutonnet** [comment] 2021-07-09 23:13
Hi again @diegodewilde sorry for the lack of response, I've not had much time to look into this.

That being said, I have a PR to toggle an option such as `preserve-yaml-order` will will not re-sort (and also keep comments): https://github.com/bitpicky/dbt-sugar/pull/305

I wanted to also check/reproduce the thing you mention about dbt-sugar messing with other yaml files. You gave me a sample of a gitlab ci yaml. I'm curious where this file lives. Do you somehow have it inside the dbt project? I assume that dbt-sugar wouldn't want to mess with files that are higher than the dbt project (in theory) so before I go further and try that if you can confirm that, that would be awesome!

**Comment by diegodewilde** [comment] 2021-07-12 15:15
Hi @bastienboutonnet, fantastic that this feature will be possible soon! 

This gitlab ci yaml file lives inside the dbt project, I didn't experience that dbt-sugar messed with files that are higher than the dbt project. 🍀

**Comment by bastienboutonnet** [comment] 2021-07-12 21:28
To be honest, I have no idea yet how and why we even manage to modify those files since we're not supposed to touch them but I just was able to reproduce it and I'm like "WUT?"

I'll have to dig a little deeper, I'm not sure if checking for something like `version: 2` would be enough or the right way to go as I'd really like to understand how on earth we feel like we have anything to do in those files but as soon as I get to the bottom of it, it should be a pretty easy sell.

I'll keep you posted.

**Comment by bastienboutonnet** [comment] 2021-07-16 06:50
Alright! @diegodewilde feel like testing out the new changes I made?

I have two changes ready:
- `--perserve-yaml-order` would cause dbt-sugar **not** to reorder yaml files. This is useful if you have comments in your model descriptor files and you don't want to lose them. Under the hood it uses a different yaml loader that allows comments keeping but makes resorting a bit hard. So that is a compromise but I think one that is ok to make for now. This is available both as a CLI arg and as a `sugar_config.yaml` variable.
- The second change is more in line with what you were originally asking and I would consider it a fix for sure: When we're about to save yaml files, we check that the content we're about to write to a file has a field called `models:` which would mean that it is indeed a model descriptor file. I'll look into this again because ideally, I want to make sure that we skip non model descriptor files from being processed at all, but to do this without copypasta was going to take longer so this is a bit of a hot fix.

For you to test it, would you like me to make a release on the test PyPI (and I can give you some instructions on how to install from that if you want) or do you feel comfortable enough to install from a certain git SHA?

I can help with either options just say which one you'd prefer.

**Comment by diegodewilde** [comment] 2021-07-16 11:49
Hi @bastienboutonnet 

This is great, seems to be working smoothly on my side and fixing the issue I experienced!
Actually, **bullet 2** on it's own ensures no yml files are changed that are not part of the dbt project. 
Many thanks for resolving this one! 

One remark though, with regards to the `--perserve-yaml-order`, it still modifies yml files within the project:
- quotes (") are removed
- reformatting is done based on line length

^ I'm not sure whether these can be considered a bug, actually I don't think so.

Would it be possible for you to provide me with an example `sugar_config.yml`?
I'm unable to get this working by adding the variable here. 


**Sidenote**
As it was my first time installing a custom branch, quickly wanted to validate the code I ran to get the newest version installed with you (_just to be sure I didn't do anything wrong - but as the new features are available, I assume it's right_): 
`pip install git+https://github.com/bitpicky/dbt-sugar.git#egg=dbt-sugar`

**Comment by bastienboutonnet** [comment] 2021-07-16 16:10
Hi @diegodewilde thanks a lot for getting around to testing it so quickly!

> Actually, bullet 2 on it's own ensures no yml files are changed that are not part of the dbt project.
Many thanks for resolving this one!

Cool yeah I'm glad we got that one covered because it was simply really bad and dangerous

Regarind the formatting, I'm sorry I must have missed the original requirements around formatting. I thought it was mainly an issue of preserving the order and comments.

> One remark though, with regards to the --perserve-yaml-order, it still modifies yml files within the project:

quotes (") are removed
reformatting is done based on line length
^ I'm not sure whether these can be considered a bug, actually I don't think so.

It's not a bug at all. It's by design more or less. And also the fact that yaml is shit and can do things in so many ways. I'm going to be annoying again. Could you send me an example of a yaml document the way you have it before and after.

I think, what we will have to do is to allow for a certain configuration options to be passed. It's very hard, I think, to not reformat since we're basically re-creating a file and the dumpers just have their preferences. Giving config options would be great but it is almost annoying to do so because it will be a lot of arguments to make available.

However, let's see an example. And do you think that the formatting changes that happen are just something that's annoying because it creates diffs that are larger than they should be or because it actually breaks something?

Depending on this we will have to make some opinionated choices I think... 

I'll reopen the issue to make sure this stays visible.


> pip install git+https://github.com/bitpicky/dbt-sugar.git#egg=dbt-sugar

I haven't done it in a while but that looks indeed totally familiar so I think you're good. I think the `#egg=dbt-sugar` part may not have been needed but I think it didn't hurt. And this led you to install the `main` branch (which is what you wanted to do anyway). If the code had been on a separate feature branch then I think you'd have wanted to add a `@<branch_or_tag_name>` or something like that. But I would double check documentation haha. I'm speaking purely from top of mind.

**Comment by diegodewilde** [comment] 2021-07-19 06:41
Hi @bastienboutonnet 
Happy monday! 🥂 

Thanks for your agreement on installing the example branch! Think it's indeed the right syntax as it worked quite well 😄 

I agree the quote removals is something that can be done, just wanted to mention that this is happening as well.

Removing comments, on the other hand, can potentially be dangerous the way we use it (to show people they can't remove anything / to remind they need to do something when changing a value or to simple refer to technical documentation). Hope you share the same opinion on that. 

I'm more than happy to create an example file for you. You can just `copy pasta` into the dbt project somewhere and call it `example_remove_comments.yml`. Actually the file name doesn't matter a lot 🙊 

Hope this is able to support you: 

```yaml
version: 2
sources:
- name: some_source_name
  description: some description #comment will be removed  (DONT REMOVE) 
  database: dummy_db_name
  schema: dummy_schema_name
  tables:
  - name: some_source_table_name
    description: Some description # Comment will be removed (DONT REMOVE) 
```

I agree on trying to keep the amount of arguments to a minimum. On the other hand, if it's configured in the `sugar_config.yml` (which worked very well for the `perserve_yaml_order`) - it doesn't bother at all. 

Cheers! 
// Diëgo

**Comment by bastienboutonnet** [comment] 2021-07-20 05:21
Thanks @diegodewilde just to check:
Dbt-sugar should leave your sources descriptors alone right? Is is not the case?

**Comment by diegodewilde** [comment] 2021-07-20 09:26
@bastienboutonnet you're totally right - it leaves sources alone (I always think dbt-sugar starts from sources as well for some reason). My bad! 

This should be a better example (using models):
```yaml
version: 2
models:
- name: some_model_name
  description: some description #comment will be removed  (DONT REMOVE) 
  columns:
  - name: some_column_name
    description: Some description # Comment will be removed (DONT REMOVE) 
 ```

**Comment by bastienboutonnet** [comment] 2021-07-20 11:02
Ok cool, and currently, even with `--preserve-yaml-order` these inline comments get removed?

**Comment by diegodewilde** [comment] 2021-07-27 08:14
They don't get removed, if I apply the `--preserve-yaml-order`. 🤔

Would it be possible for you to provide me with an example `sugar_config.yml` file so I can check with this configuration set as default?

**Comment by bastienboutonnet** [comment] 2021-07-28 08:43
@diegodewilde 

Ok so that's good then if they do not get remove. I assume that this means we could close this issue and document the use of the flags in the coming days.

I am not sure what you wanted to see in an example, and since I don't have a full example of all possible combinations of the `sugar_config.yaml` I'll point you to the code that defines the schema and types of the sugar config:

https://github.com/bitpicky/dbt-sugar/blob/main/dbt_sugar/core/config/config.py#L19-L50

So for this particular example you would need to add `preserve_yaml_order: true` in the syrup

so something like:
```yaml
syrups:
- name: foo
  ...
  preserve_yaml_order: true
```

**Comment by diegodewilde** [comment] 2021-07-28 09:19
Hi @bastienboutonnet 

Great - thanks to provide me with an example. It's exactly what I've added, but it seems dbt-sugar doesn't take the configuration from there for some reason. 

However, adding the argument `--preserve-yaml-order` works perfectly and leaves the comments as they are - which is really awesome! 💯

**Comment by bastienboutonnet** [comment] 2021-07-28 11:08
@diegodewilde that's weird, maybe something funky is happening with the CLI override step.

Just one question how do you run dbt-sugar? do you excplicily pass a `--syrup <syrup name>` argument or you have the syrup configured as a default as shown in the docs (https://bitpicky.gitbook.io/dbt-sugar/installation-and-configuration/configuration/sugar-config)

Just to rule out the fact that maybe you added it to a syrup that dbt-sugar does not actually run. I'll have try and reproduce it later today or look into the code.

**Comment by diegodewilde** [comment] 2021-07-28 11:49
I have the syrup configured as a default as shown in the docs (only using one syrup).

**Comment by bastienboutonnet** [comment] 2021-07-28 12:09
Ok! then I guess there is a bug in my implementation. I'll have a look at the end of the day when I'm done with work. It's probably something silly that I didn't test properly.

**Closed** 2021-07-28 16:09 UTC
Labels: bug, enhancement, topic: cli interface, type: task

**Comment by bastienboutonnet** [comment] 2021-07-28 16:12
Hi again @diegodewilde I found the issue on why the sugar config setting was overridden... If you install from the latest commit on the main branch and give it a go all should be good now. Can you confirm? I just tested it locally and it seems to work but I want to make extra sure.

If all is good I'll cut a proper release for this.

Then we'll have to discuss the formatting and indentation stuff but I think this will take some time and agreement. I don't consider this a bug or blocker though.

**Comment by diegodewilde** [comment] 2021-07-29 08:18
Hi @bastienboutonnet 

I've just installed from the latest commit on the main branch and tested it out... It works! 🎉 🍾 
Going to work with dbt-sugar quite intensively in the coming months, it's great to have all documentation up-to-date with a single command! Big thanks for your efforts! 

With regards to the formatting and indentation I agree that it's not a blocker or bug, it's more something to be aware of. Maybe it's even a feature! 😉

Looking forward to the official release including this change! 

Cheers
// Diëgo

**Comment by bastienboutonnet** [comment] 2021-07-29 08:30
> I've just installed from the latest commit on the main branch and tested it out... It works! 🎉 🍾

This is great news @diegodewilde 

> Going to work with dbt-sugar quite intensively in the coming months, it's great to have all documentation up-to-date with a single command! Big thanks for your efforts!

Even more great news! Do not hesitate to let us know if there are weird things or UI improvements we should consider. It's really good to have users who are going to use it intensively so we can make sure we can make it better. I, sadly, don't use dbt much these days at my new gig so I don't have the chance to eat my own dogfood yet.

> With regards to the formatting and indentation I agree that it's not a blocker or bug, it's more something to be aware of. Maybe it's even a feature! 😉

I'll make a ticket to have this thought about. I think we could allow for a certain amount of configuration such as indentation etc to be configurable.

> Looking forward to the official release including this change!

I'll try and cut one today, but I might want to do this when I have documented also in gitbook so that might take a little longer.

**Comment by bastienboutonnet** [comment] 2021-07-30 13:04
@diegodewilde v0.1.0 is out on PyPI so you can now install it via pip by doing `pip install -U dbt-sugar` happy documenting!
